# permissions for end users to view fenceagentsremediations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fenceagentsremediation-viewer-role
rules:
- apiGroups:
  - fence-agents-remediation.medik8s.io
  resources:
  - fenceagentsremediations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - fence-agents-remediation.medik8s.io
  resources:
  - fenceagentsremediations/status
  verbs:
  - get
