---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - deletecollection
  - get
  - list
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods/exec
  verbs:
  - create
- apiGroups:
  - fence-agents-remediation.medik8s.io
  resources:
  - fenceagentsremediations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - fence-agents-remediation.medik8s.io
  resources:
  - fenceagentsremediations/finalizers
  verbs:
  - update
- apiGroups:
  - fence-agents-remediation.medik8s.io
  resources:
  - fenceagentsremediations/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - fence-agents-remediation.medik8s.io
  resources:
  - fenceagentsremediationtemplates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
