## Append samples you want in your CSV to this file as resources ##
resources:
- fence-agents-remediation_v1alpha1_fenceagentsremediation.yaml
- fence-agents-remediation_v1alpha1_fenceagentsremediationtemplate.yaml
#+kubebuilder:scaffold:manifestskustomizesamples
